name: WEB-011 - MICROSERVICES - Platform

on:
  push:
    branches:
      - "PlatformService"
  pull_request:
    branches:
      - "PlatformService"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git Config
        run: |
          git config user.name "Stephen Phyo"
          git config user.email "stephenphyo2019.official@gmail.com"

      - name: Save Version
        id: version
        run: echo ::set-output name=tag

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Build & Push to Docker Hub Repository
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile.prod
          tags: stephenphyo/web-011-microservices:platform-latest

  deploy:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull Docker Image, Replace & Restart Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_HOSTNAME }}
          username: ${{ secrets.DEPLOYMENT_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_SERVER_PASSWORD }}
          script: |
            docker stop web-011-microservices-platform || true
            docker rm web-011-microservices-platform || true
            docker rmi docker.io/stephenphyo/web-011-microservices:platform-latest || true
            docker image pull --platform linux/x86_64 docker.io/stephenphyo/web-011-microservices:platform-latest || true
            docker run -d --name web-011-microservices-platform --restart unless-stopped -p 5011:80 -p 7011:443 --platform linux/arm64 docker.io/stephenphyo/web-011-microservices:platform-latest
